=== BenRasha/26_JavaST_2021/Task08XML_WebParsing/src/main/resources/periodical.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://www.training.by/entities"
        xmlns:tns="http://www.training.by/entities"
        elementFormDefault="qualified">
    <element name="papers">
        <complexType>
            <sequence>
                <element name="paper"
                         type="tns:Paper"
                         minOccurs="1"
                         maxOccurs="unbounded"/>
            </sequence>
        </complexType>
    </element>
    <element name="paper" type="tns:Paper" abstract="true"/>

    <complexType name="Paper">
        <sequence>
            <element name="title" type="string"/>
            <element name="type">
                <simpleType>
                    <restriction base="string">
                        <enumeration value="Newspaper"/>
                        <enumeration value="Magazine"/>
                        <enumeration value="Booklet"/>
                    </restriction>
                </simpleType>
            </element>
            <element name="monthly">
                <simpleType>
                    <restriction base="string">
                        <enumeration value="Weekly"/>
                        <enumeration value="Monthly"/>
                        <enumeration value="Yearly"/>
                    </restriction>
                </simpleType>
            </element>
            <element name="chars" type="tns:Char"/>
        </sequence>
        <attribute name="id" type="string" use="required"/>
    </complexType>

    <complexType name="Char">
        <sequence>
            <element name="colour" type="boolean"/>
            <element name="capacity">
                <simpleType>
                    <restriction base="positiveInteger">
                        <minInclusive value="1"/>
                        <maxInclusive value="1000"/>
                    </restriction>
                </simpleType>
            </element>
            <element name="cover" default="Paper">
                <simpleType>
                    <restriction base="string">
                        <enumeration value="Glossy"/>
                        <enumeration value="Paper"/>
                    </restriction>
                </simpleType>
            </element>
        </sequence>
    </complexType>
</schema>

=== BenRasha/26_JavaST_2021/Task08XML_WebParsing/src/main/resources/periodical.xml
<?xml version="1.0" encoding="UTF-8" ?>
<papers xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xmlns="http://www.training.by/entities"
        xsi:schemaLocation="http://www.training.by/entities  periodical.xsd">
    <paper id="345">
        <title>Sport News</title>
        <type>Booklet</type>
        <monthly>Monthly</monthly>
        <chars>
            <colour>true</colour>
            <capacity>150</capacity>
            <cover>Glossy</cover>
        </chars>
    </paper>
    <paper id="2678">
        <title>Daily News</title>
        <type>Newspaper</type>
        <monthly>Weekly</monthly>
        <chars>
            <colour>true</colour>
            <capacity>800</capacity>
            <cover>Paper</cover>
        </chars>
    </paper>
    <paper id="020421">
        <title>BBC News</title>
        <type>Newspaper</type>
        <monthly>Monthly</monthly>
        <chars>
            <colour>false</colour>
            <capacity>500</capacity>
            <cover>Paper</cover>
        </chars>
    </paper>
    <paper id="123485">
        <title>Cosmopolitan</title>
        <type>Magazine</type>
        <monthly>Yearly</monthly>
        <chars>
            <colour>true</colour>
            <capacity>400</capacity>
            <cover>Glossy</cover>
        </chars>
    </paper>
    <paper id="1234124">
        <title>Naviny</title>
        <type>Newspaper</type>
        <monthly>Weekly</monthly>
        <chars>
            <colour>true</colour>
            <capacity>450</capacity>
            <cover>Paper</cover>
        </chars>
    </paper>
    <paper id="123125">
        <title>GQ</title>
        <type>Magazine</type>
        <monthly>Yearly</monthly>
        <chars>
            <colour>true</colour>
            <capacity>500</capacity>
            <cover>Glossy</cover>
        </chars>
    </paper>
    <paper id="04359346">
        <title>Loudwire</title>
        <type>Magazine</type>
        <monthly>Weekly</monthly>
        <chars>
            <colour>true</colour>
            <capacity>200</capacity>
            <cover>Glossy</cover>
        </chars>
    </paper>
    <paper id="45747345">
        <title>Sun</title>
        <type>Newspaper</type>
        <monthly>Monthly</monthly>
        <chars>
            <colour>false</colour>
            <capacity>700</capacity>
            <cover>Paper</cover>
        </chars>
    </paper>
    <paper id="12395235">
        <title>Daily News</title>
        <type>Newspaper</type>
        <monthly>Weekly</monthly>
        <chars>
            <colour>false</colour>
            <capacity>350</capacity>
            <cover>Paper</cover>
        </chars>
    </paper>
    <paper id="9379543">
        <title>Sports</title>
        <type>Booklet</type>
        <monthly>Yearly</monthly>
        <chars>
            <colour>false</colour>
            <capacity>500</capacity>
            <cover>Glossy</cover>
        </chars>
    </paper>
    <paper id="112341">
        <title>Modern Technology</title>
        <type>Newspaper</type>
        <monthly>Monthly</monthly>
        <chars>
            <colour>false</colour>
            <capacity>670</capacity>
            <cover>Paper</cover>
        </chars>
    </paper>
    <paper id="14572349">
        <title>Euronews</title>
        <type>Newspaper</type>
        <monthly>Weekly</monthly>
        <chars>
            <colour>false</colour>
            <capacity>200</capacity>
            <cover>Paper</cover>
        </chars>
    </paper>
    <paper id="82199532">
        <title>Modern World</title>
        <type>Magazine</type>
        <monthly>Monthly</monthly>
        <chars>
            <colour>true</colour>
            <capacity>650</capacity>
            <cover>Glossy</cover>
        </chars>
    </paper>
    <paper id="12938432">
        <title>All About Music</title>
        <type>Booklet</type>
        <monthly>Yearly</monthly>
        <chars>
            <colour>true</colour>
            <capacity>900</capacity>
            <cover>Glossy</cover>
        </chars>
    </paper>
    <paper id="12388">
        <title>Belaya Niva</title>
        <type>Newspaper</type>
        <monthly>Weekly</monthly>
        <chars>
            <colour>false</colour>
            <capacity>200</capacity>
            <cover>Paper</cover>
        </chars>
    </paper>
    <paper id="123874">
        <title>Suburban</title>
        <type>Magazine</type>
        <monthly>Weekly</monthly>
        <chars>
            <colour>true</colour>
            <capacity>300</capacity>
            <cover>Glossy</cover>
        </chars>
    </paper>
</papers>
